apiVersion: v1
kind: Service
metadata:
  name: sketchbrain-ui-svc
  labels:
    app: sketchbrain-ui
spec:
  type: ClusterIP
  ports:
    - name: ui-port
      port: 3000
      targetPort: 3000
  selector:
    app: sketchbrain-ui
